Algoritmo "exerc11"

Var
a, b, c, delta: real
Inicio
escreva("insira o valor de A: ")
leia(a)
escreva("insira o valor de B: ")
leia(b)
escreva("insira o valor de C: ")
leia(c)

escreval
escreval("|delta = b(2) – 4ac| --> (fórmula da equação.)")
escreval("delta = ", b,"^2 – 4 (", a,") * (", c,")")

delta <- ((b^2) - 4 * a * c)

escreval
escreva ("valor de delta é: " , delta)
escreval
Fimalgoritmo