Algoritmo "exerc20"
//20) Desenvolva um programa que leia um número inteiro e mostre
//se ele é PAR ou IMPAR.
Var
   num: inteiro
Inicio
   escreva("- Insira um numero: ")
   leia(num)
   escreva("---------------------------")
   escreval

   se(num % 2 = 0) entao
      escreval
      escreva("> O numero inserido é PAR.")
   senao
      escreval
      escreva("> O numero inserido é ÍMPAR.")
   fimse
   escreval
   escreval
Fimalgoritmo